# Generated by Django 5.0.4 on 2024-04-12 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.PositiveBigIntegerField()),
                ('url', models.URLField(max_length=400)),
                ('note', models.TextField()),
                ('groups', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('domainID', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupID', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('noteID', models.AutoField(primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('createdBy', models.PositiveIntegerField()),
                ('createdAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.PositiveBigIntegerField()),
                ('token', models.CharField(max_length=255)),
                ('expiresAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('urlID', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('emailID', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DomainConfiguration',
            fields=[
                ('configurationID', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=255)),
                ('keys', models.JSONField()),
                ('domainID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.domain')),
            ],
        ),
        migrations.CreateModel(
            name='NoteGroupRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('noteID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.note')),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='urlID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.url'),
        ),
        migrations.CreateModel(
            name='UserGroupRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
